
#spring.datasource.url=jdbc:mysql://apipl-db.clc9wkbwagzw.ap-northeast-2.rds.amazonaws.com:3306/oapdb
#spring.datasource.username=admin
#spring.datasource.password=dbfrhrfh1rk!
#spring.datasource.url=jdbc:mysql://192.168.1.254:3306/oapdb?useSSL=false

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=dbfrhrfh1rk!

#spring.security.user.name=user
#spring.security.user.password=password

spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/?serverTimezone=UTC
  username: root
  password: dbfrhrfh1rk!

 redis:
  host: 127.0.0.1
  password: dbfrhrfh1rk!
  port: 6379
  timeout: 0
 
 
 security.user:
   name: user
   password: password